#!/usr/bin/env python
"""Usage:
    cardsort to-matrix <file>
"""

import sys

from docopt import docopt
from planning_tools import CardSort

def main():
    arguments = docopt(__doc__)

    c = CardSort()
    if arguments['to-matrix']:
        if arguments['<file>'] == '-':
            f = sys.stdin
        else:
            f = open(arguments['<file>'], 'r')
        c.import_from_csv(f)
    sys.stdout.write(c.csv())


if __name__=='__main__':
    main()
