#!/usr/bin/env python
"""Usage:
    matrix cluster [--linkage_method=<linkage_method>] <file>
    matrix to-ascii <file>
    matrix histogram <file>

   Arguments:
    linkage_method: single
                    complete
                    average
                    weighted
                    median
                    ward
"""

import sys

from docopt import docopt
from planning_tools import Matrix


def main():
    arguments = docopt(__doc__)

    m = Matrix()
    if arguments['<file>'] == '-':
        f = sys.stdin
    else:
        f = open(arguments['<file>'], 'r')
    m.import_from_csv(sys.stdin)

    if arguments['cluster']:
        if arguments['--linkage_method']:
            m.cluster(arguments['--linkage_method'])
        else:
            m.cluster()
            sys.stdout.write(m.csv())
            sys.exit()
    elif arguments['histogram']:
        m.histogram()
        sys.exit()
    elif arguments['randomize']:
        m.randomize()
        sys.stdout.write(m.csv())
        sys.exit()


if __name__ == '__main__':
    main()
