#!/usr/bin/env python
"""Usage:
    pairwise <linkage-method> <file>

   Arguments:
    linkage_method: single
                    complete
                    average
                    weighted
                    median
                    ward
"""
import sys

from docopt import docopt
from classes import Matrix


def main():
    arguments = docopt(__doc__)

    m = Matrix()
    if arguments['<file>'] == '-':
        f = sys.stdin
    else:
        f = open(arguments['<file>'], 'r')
    m.import_from_csv(f)

    m.cluster(arguments['<linkage-method>'])
    sys.stdout.write(m.csv())


if __name__ == '__main__':
    main()
