#!/usr/bin/env python
"""Usage:
    similarity to-matrix <file>
"""

import sys

from docopt import docopt
from planning_tools import Similarity


def main():
    arguments = docopt(__doc__)

    s = Similarity()
    if arguments['to-matrix']:
        if arguments['<file>'] == '-':
            f = sys.stdin
        else:
            f = open(arguments['<file>'], 'r')
        s.import_from_csv(f)
    sys.stdout.write(s.csv())


if __name__ == '__main__':
    main()
